In [80]:
# Importar Libraries
import pandas as pd
import openpyxl
import copy
from random import choice

In [81]:
# Dar um nome simples ao ficheiro de Excel a utilizar
exc_pessoas = r'SecretSantaDataSet.xlsx'

In [82]:
# Abrir o ficheiro Excel
wb = openpyxl.load_workbook(exc_pessoas)

In [83]:
# Abrir a worksheet do ficheiro
ws_pessoas = wb['Pessoas']

In [84]:
# Criar uma dataframe com os dados do ficheiro de Excel
# Iniciar uma espécie de apontador. Começa na primeira linha e primeira coluna do ficheiro
data_pessoas = ws_pessoas.values

# Get the first line in file as a header line
columns_pessoas = next(data_pessoas)

# Create a DataFrame based on subsequent lines of data. Use as headers the list obtained in the previous command
df_pessoas = pd.DataFrame(data_pessoas, columns=columns_pessoas)

In [85]:
# Comando de teste, para remover antes de entregar
df_pessoas.head()

                                 Nome  Grupo  Turma
0              DIANA RIBEIRO FERREIRA      1      2
1      GUSTAVO JORGE MONTEIRO PACHECO      1      2
2  BERNARDO MIGUEL RODRIGUES SEQUEIRA      1      2
3             TIAGO NUNES MENDES MOÇO      2      2
4      PEDRO MIGUEL DOS SANTOS ALBANO      2      2

In [86]:
# Inclusão em dicionário de lista com nome e nrº do grupo
dic_pessoas = {}

dic_pessoas = df_pessoas.iloc[0:,0:2].groupby('Nome')['Grupo'].agg(list).to_dict()

In [87]:
# Comando de teste, para remover antes de entregar
print(dic_pessoas)

{'AFONSO JOSÉ FERNANDES CARDOSO RODRIGUES': [16], 'ANA FILIPA GONÇALVES SIMÕES': [12], 'ANA RITA LOPES BORGES MARTINS': [11], 'ANA SOPHIA SILVEIRA FIGUEIREDO': [10], 'ANDRÉ DE NORONHA BEBIANO E MOURA': [4], 'ANDRÉ MIGUEL LEONG RUELA': [7], 'ANTONIO OLIVEIRA LIMA': [5], 'BERNARDO MIGUEL RODRIGUES SEQUEIRA': [1], 'BIANCA BASTOS DOS SANTOS': [10], 'CATARINA ISABEL ALVES DA COSTA': [11], 'CÁTIA RAQUEL AFONSO AGUDO NEVES': [4], 'DAVID COSTA SECO': [10], 'DIANA RIBEIRO FERREIRA': [1], 'EMANUEL JOSÉ ALAGO RODRIGUES': [2], 'GLÓRIA BONIQUET': [3], 'GUSTAVO JORGE MONTEIRO PACHECO': [1], 'GUSTAVO LUNA BRASILEIRO': [7], 'IRINA ADAM CRESPO QUEIRÓS': [9], 'ISABELA MOREIRA MERELLES': [13], 'JOEL ANDRÉ ANTUNES BERNARDO': [8], 'JOÃO MARIA ATAÍDE DE FIGUEIREDO CABRAL DA CÂMARA': [17], 'JOÃO PEDRO LOPES FERNANDES': [16], 'JUAN GABRIEL RUIZ CASTILLO': [7], 'JULIA REGINA SCOTTI': [14], 'LAURA MIGUEL ZEVERINO RIBEIRO': [3], 'LILIANA FRAZÃO VALA': [15], 'LUIS PEDRO AZEVEDO ALMEIDA MACHADO': [12], 'LUÍS GONÇALO VALENTE INFANTE': [16], 'MADALENA DOS REIS PEREIRA PATACO': [5], 'MARIA ANA ATAÍDE DE FIGUEIREDO CABRAL DA CAMARA': [17], 'MARIANA HENRIQUES RAPOSO MARQUES TAVARES': [5], 'MARTA SOFIA SEVERO PIRES': [6], 'MIGUEL DE FREITAS NUNES PEREIRA': [8], 'MIGUEL JOSÉ DE CASTRO FAUSTINO': [4], 'MÓNICA HORTA DE FIGUEIREDO': [12], 'NUNO CLÁUDIO FERREIRA ROSA': [7], 'NUNO NOGUEIRA DA SILVA': [2], 'PEDRO MARIA ATAIDE FIGUEIREDO CABRAL DA CAMARA': [17], 'PEDRO MIGUEL DOS SANTOS ALBANO': [2], 'PRIAL BHARAT': [9], 'RICARDO MIGUEL REIS DUARTE': [12], 'RITA ISABEL LARANJEIRA COSTA RIBEIRO': [9], 'RITA MARIA BRANCO DE ARAÚJO': [3], 'RUI MIGUEL DA FONSECA MATIAS': [16], 'RUTE ALEXANDRA CASTRO LOPES': [10], 'SAMUEL MARTINS FILIPE': [8], 'SUSANA DOS SANTOS CARAPUÇA ROSADO': [11], 'TAINÁ REIS MANESCHY': [5], 'TIAGO NUNES MENDES MOÇO': [2], 'TIAGO VASQUES ENDERENÇO': [9], 'TIAGO VÍTOR PINHEIRO VALENTE FARIA': [4], 'VASCO MIGUEL FERNANDES ALBERTO WILTON PEREIRA': [3]}

In [90]:
# Inicializa o dicionário "grupos" no qual agregamos em lista os nomes por nrº de grupo
dic_grupos = {}

dic_grupos = df_pessoas.iloc[0:, 0:2].groupby('Grupo')['Nome'].agg(list).to_dict()

In [91]:
# Comando de teste, para remover antes de entregar
print(dic_grupos)

{1: ['DIANA RIBEIRO FERREIRA', 'GUSTAVO JORGE MONTEIRO PACHECO', 'BERNARDO MIGUEL RODRIGUES SEQUEIRA'], 2: ['TIAGO NUNES MENDES MOÇO', 'PEDRO MIGUEL DOS SANTOS ALBANO', 'NUNO NOGUEIRA DA SILVA', 'EMANUEL JOSÉ ALAGO RODRIGUES'], 3: ['RITA MARIA BRANCO DE ARAÚJO', 'LAURA MIGUEL ZEVERINO RIBEIRO', 'VASCO MIGUEL FERNANDES ALBERTO WILTON PEREIRA', 'GLÓRIA BONIQUET'], 4: ['ANDRÉ DE NORONHA BEBIANO E MOURA', 'TIAGO VÍTOR PINHEIRO VALENTE FARIA', 'MIGUEL JOSÉ DE CASTRO FAUSTINO', 'CÁTIA RAQUEL AFONSO AGUDO NEVES'], 5: ['TAINÁ REIS MANESCHY', 'MARIANA HENRIQUES RAPOSO MARQUES TAVARES', 'ANTONIO OLIVEIRA LIMA', 'MADALENA DOS REIS PEREIRA PATACO'], 6: ['MARTA SOFIA SEVERO PIRES'], 7: ['NUNO CLÁUDIO FERREIRA ROSA', 'ANDRÉ MIGUEL LEONG RUELA', 'GUSTAVO LUNA BRASILEIRO', 'JUAN GABRIEL RUIZ CASTILLO'], 8: ['JOEL ANDRÉ ANTUNES BERNARDO', 'SAMUEL MARTINS FILIPE', 'MIGUEL DE FREITAS NUNES PEREIRA'], 9: ['RITA ISABEL LARANJEIRA COSTA RIBEIRO', 'IRINA ADAM CRESPO QUEIRÓS', 'TIAGO VASQUES ENDERENÇO', 'PRIAL BHARAT'], 10: ['RUTE ALEXANDRA CASTRO LOPES', 'ANA SOPHIA SILVEIRA FIGUEIREDO', 'DAVID COSTA SECO', 'BIANCA BASTOS DOS SANTOS'], 11: ['ANA RITA LOPES BORGES MARTINS', 'CATARINA ISABEL ALVES DA COSTA', 'SUSANA DOS SANTOS CARAPUÇA ROSADO'], 12: ['RICARDO MIGUEL REIS DUARTE', 'ANA FILIPA GONÇALVES SIMÕES', 'LUIS PEDRO AZEVEDO ALMEIDA MACHADO', 'MÓNICA HORTA DE FIGUEIREDO'], 13: ['ISABELA MOREIRA MERELLES'], 14: ['JULIA REGINA SCOTTI'], 15: ['LILIANA FRAZÃO VALA'], 16: ['LUÍS GONÇALO VALENTE INFANTE', 'AFONSO JOSÉ FERNANDES CARDOSO RODRIGUES', 'JOÃO PEDRO LOPES FERNANDES', 'RUI MIGUEL DA FONSECA MATIAS'], 17: ['JOÃO MARIA ATAÍDE DE FIGUEIREDO CABRAL DA CÂMARA', 'MARIA ANA ATAÍDE DE FIGUEIREDO CABRAL DA CAMARA', 'PEDRO MARIA ATAIDE FIGUEIREDO CABRAL DA CAMARA']}

In [92]:
### IN PROGRESS ###

# Definir incompatibilidades para a segunda worksheet

# NO! for key, value in dic_grups.items():

#def find_incompatibilities(nome_sorteado):
#    for i in dic_grupos.values():
#        if i == nome_sorteado:
#            gr = dic_grupos.get.keys()
#    nome_sorteado
#    inc_peers = []
    

#i = 1
#for j in students.values(1)

In [93]:
# Criar uma cópia do dicionário com os detalhes de cada pessoa
amigo_secreto = copy.deepcopy(dic_pessoas)

In [95]:
# Sorteio dos amigos secretos
# Opção auto_sorteio = False -> não permite uma pessoa calhar a si própria
# Opção mesmo_grupo = False -> não vai permitir sorteios inter grupos

auto_sorteio = False
mesmo_grupo = False

resortear = True
cont = 0

while resortear == True:
    amigo_secreto = copy.deepcopy(dic_pessoas)
    sorteio = set(amigo_secreto.keys())
    resortear = False
    matches = []
    
    for pessoa in amigo_secreto.keys():
        sorteio_valido = sorteio.copy()

        # Remove do sorteio as pessoas do mesmo grupo
        if not mesmo_grupo:
            num_grupo = amigo_secreto.values()
            grupo = dic_grupos.keys()
            sorteio_valido = {k: amigo_secreto[k] for k in amigo_secreto.keys() - {'Grupo'}}
        elif not auto_sorteio:
            sorteio_valido.discard(pessoa)

        # Retorna a pessoa sorteada (a quem a prenda será oferecida)
        if len(sorteio_valido)>0:
            sorteado = choice(list(sorteio_valido))
            sorteio.discard(sorteado)
        else:
            resortear = True
            cont+=1
        amigo_secreto[pessoa].append(sorteado)
        # O sorteado fica armazenado na 4ª posição da lista correspondente a cada chave do dicionário amigo_secreto
        matches.append([pessoa, sorteado])
        

print(matches)
False
cont - 0

[['AFONSO JOSÉ FERNANDES CARDOSO RODRIGUES', 'PEDRO MIGUEL DOS SANTOS ALBANO'], ['ANA FILIPA GONÇALVES SIMÕES', 'TIAGO VÍTOR PINHEIRO VALENTE FARIA'], ['ANA RITA LOPES BORGES MARTINS', 'LUÍS GONÇALO VALENTE INFANTE'], ['ANA SOPHIA SILVEIRA FIGUEIREDO', 'LILIANA FRAZÃO VALA'], ['ANDRÉ DE NORONHA BEBIANO E MOURA', 'ANTONIO OLIVEIRA LIMA'], ['ANDRÉ MIGUEL LEONG RUELA', 'MÓNICA HORTA DE FIGUEIREDO'], ['ANTONIO OLIVEIRA LIMA', 'DAVID COSTA SECO'], ['BERNARDO MIGUEL RODRIGUES SEQUEIRA', 'BIANCA BASTOS DOS SANTOS'], ['BIANCA BASTOS DOS SANTOS', 'PEDRO MARIA ATAIDE FIGUEIREDO CABRAL DA CAMARA'], ['CATARINA ISABEL ALVES DA COSTA', 'CÁTIA RAQUEL AFONSO AGUDO NEVES'], ['CÁTIA RAQUEL AFONSO AGUDO NEVES', 'MARIANA HENRIQUES RAPOSO MARQUES TAVARES'], ['DAVID COSTA SECO', 'AFONSO JOSÉ FERNANDES CARDOSO RODRIGUES'], ['DIANA RIBEIRO FERREIRA', 'NUNO NOGUEIRA DA SILVA'], ['EMANUEL JOSÉ ALAGO RODRIGUES', 'MIGUEL DE FREITAS NUNES PEREIRA'], ['GLÓRIA BONIQUET', 'RITA MARIA BRANCO DE ARAÚJO'], ['GUSTAVO JORGE MONTEIRO PACHECO', 'LILIANA FRAZÃO VALA'], ['GUSTAVO LUNA BRASILEIRO', 'IRINA ADAM CRESPO QUEIRÓS'], ['IRINA ADAM CRESPO QUEIRÓS', 'GUSTAVO JORGE MONTEIRO PACHECO'], ['ISABELA MOREIRA MERELLES', 'MÓNICA HORTA DE FIGUEIREDO'], ['JOEL ANDRÉ ANTUNES BERNARDO', 'SAMUEL MARTINS FILIPE'], ['JOÃO MARIA ATAÍDE DE FIGUEIREDO CABRAL DA CÂMARA', 'RICARDO MIGUEL REIS DUARTE'], ['JOÃO PEDRO LOPES FERNANDES', 'ANA FILIPA GONÇALVES SIMÕES'], ['JUAN GABRIEL RUIZ CASTILLO', 'ISABELA MOREIRA MERELLES'], ['JULIA REGINA SCOTTI', 'RITA ISABEL LARANJEIRA COSTA RIBEIRO'], ['LAURA MIGUEL ZEVERINO RIBEIRO', 'CATARINA ISABEL ALVES DA COSTA'], ['LILIANA FRAZÃO VALA', 'JULIA REGINA SCOTTI'], ['LUIS PEDRO AZEVEDO ALMEIDA MACHADO', 'NUNO CLÁUDIO FERREIRA ROSA'], ['LUÍS GONÇALO VALENTE INFANTE', 'SUSANA DOS SANTOS CARAPUÇA ROSADO'], ['MADALENA DOS REIS PEREIRA PATACO', 'CÁTIA RAQUEL AFONSO AGUDO NEVES'], ['MARIA ANA ATAÍDE DE FIGUEIREDO CABRAL DA CAMARA', 'NUNO CLÁUDIO FERREIRA ROSA'], ['MARIANA HENRIQUES RAPOSO MARQUES TAVARES', 'IRINA ADAM CRESPO QUEIRÓS'], ['MARTA SOFIA SEVERO PIRES', 'ANDRÉ DE NORONHA BEBIANO E MOURA'], ['MIGUEL DE FREITAS NUNES PEREIRA', 'JOEL ANDRÉ ANTUNES BERNARDO'], ['MIGUEL JOSÉ DE CASTRO FAUSTINO', 'LUIS PEDRO AZEVEDO ALMEIDA MACHADO'], ['MÓNICA HORTA DE FIGUEIREDO', 'ANA FILIPA GONÇALVES SIMÕES'], ['NUNO CLÁUDIO FERREIRA ROSA', 'JOÃO MARIA ATAÍDE DE FIGUEIREDO CABRAL DA CÂMARA'], ['NUNO NOGUEIRA DA SILVA', 'GUSTAVO LUNA BRASILEIRO'], ['PEDRO MARIA ATAIDE FIGUEIREDO CABRAL DA CAMARA', 'MARIANA HENRIQUES RAPOSO MARQUES TAVARES'], ['PEDRO MIGUEL DOS SANTOS ALBANO', 'NUNO CLÁUDIO FERREIRA ROSA'], ['PRIAL BHARAT', 'VASCO MIGUEL FERNANDES ALBERTO WILTON PEREIRA'], ['RICARDO MIGUEL REIS DUARTE', 'ANTONIO OLIVEIRA LIMA'], ['RITA ISABEL LARANJEIRA COSTA RIBEIRO', 'MÓNICA HORTA DE FIGUEIREDO'], ['RITA MARIA BRANCO DE ARAÚJO', 'PEDRO MARIA ATAIDE FIGUEIREDO CABRAL DA CAMARA'], ['RUI MIGUEL DA FONSECA MATIAS', 'DIANA RIBEIRO FERREIRA'], ['RUTE ALEXANDRA CASTRO LOPES', 'GUSTAVO LUNA BRASILEIRO'], ['SAMUEL MARTINS FILIPE', 'ANTONIO OLIVEIRA LIMA'], ['SUSANA DOS SANTOS CARAPUÇA ROSADO', 'ANDRÉ MIGUEL LEONG RUELA'], ['TAINÁ REIS MANESCHY', 'ANDRÉ MIGUEL LEONG RUELA'], ['TIAGO NUNES MENDES MOÇO', 'EMANUEL JOSÉ ALAGO RODRIGUES'], ['TIAGO VASQUES ENDERENÇO', 'MARIANA HENRIQUES RAPOSO MARQUES TAVARES'], ['TIAGO VÍTOR PINHEIRO VALENTE FARIA', 'AFONSO JOSÉ FERNANDES CARDOSO RODRIGUES'], ['VASCO MIGUEL FERNANDES ALBERTO WILTON PEREIRA', 'TIAGO VASQUES ENDERENÇO']]

0

In [96]:
# Criar um dataframe com os resultados para posterior escrita em Excel
df_matches = pd.DataFrame(matches, columns=['Gift Giver', 'Gift Receiver'])

In [97]:
# Comando de teste, para remover antes de entregar
df_matches

,Gift Giver,Gift Receiver
0,AFONSO JOSÉ FERNANDES CARDOSO RODRIGUES,PEDRO MIGUEL DOS SANTOS ALBANO
1,ANA FILIPA GONÇALVES SIMÕES,TIAGO VÍTOR PINHEIRO VALENTE FARIA
2,ANA RITA LOPES BORGES MARTINS,LUÍS GONÇALO VALENTE INFANTE
3,ANA SOPHIA SILVEIRA FIGUEIREDO,LILIANA FRAZÃO VALA
4,ANDRÉ DE NORONHA BEBIANO E MOURA,ANTONIO OLIVEIRA LIMA
5,ANDRÉ MIGUEL LEONG RUELA,MÓNICA HORTA DE FIGUEIREDO
6,ANTONIO OLIVEIRA LIMA,DAVID COSTA SECO
7,BERNARDO MIGUEL RODRIGUES SEQUEIRA,BIANCA BASTOS DOS SANTOS
8,BIANCA BASTOS DOS SANTOS,PEDRO MARIA ATAIDE FIGUEIREDO CABRAL DA CAMARA
9,CATARINA ISABEL ALVES DA COSTA,CÁTIA RAQUEL AFONSO AGUDO NEVES
10,CÁTIA RAQUEL AFONSO AGUDO NEVES,MARIANA HENRIQUES RAPOSO MARQUES TAVARES
11,DAVID COSTA SECO,AFONSO JOSÉ FERNANDES CARDOSO RODRIGUES
12,DIANA RIBEIRO FERREIRA,NUNO NOGUEIRA DA SILVA
13,EMANUEL JOSÉ ALAGO RODRIGUES,MIGUEL DE FREITAS NUNES PEREIRA
14,GLÓRIA BONIQUET,RITA MARIA BRANCO DE ARAÚJO
15,GUSTAVO JORGE MONTEIRO PACHECO,LILIANA FRAZÃO VALA
16,GUSTAVO LUNA BRASILEIRO,IRINA ADAM CRESPO QUEIRÓS
17,IRINA ADAM CRESPO QUEIRÓS,GUSTAVO JORGE MONTEIRO PACHECO
18,ISABELA MOREIRA MERELLES,MÓNICA HORTA DE FIGUEIREDO
19,JOEL ANDRÉ ANTUNES BERNARDO,SAMUEL MARTINS FILIPE
20,JOÃO MARIA ATAÍDE DE FIGUEIREDO CABRAL DA CÂMARA,RICARDO MIGUEL REIS DUARTE
21,JOÃO PEDRO LOPES FERNANDES,ANA FILIPA GONÇALVES SIMÕES
22,JUAN GABRIEL RUIZ CASTILLO,ISABELA MOREIRA MERELLES
23,JULIA REGINA SCOTTI,RITA ISABEL LARANJEIRA COSTA RIBEIRO
24,LAURA MIGUEL ZEVERINO RIBEIRO,CATARINA ISABEL ALVES DA COSTA
25,LILIANA FRAZÃO VALA,JULIA REGINA SCOTTI
26,LUIS PEDRO AZEVEDO ALMEIDA MACHADO,NUNO CLÁUDIO FERREIRA ROSA
27,LUÍS GONÇALO VALENTE INFANTE,SUSANA DOS SANTOS CARAPUÇA ROSADO
28,MADALENA DOS REIS PEREIRA PATACO,CÁTIA RAQUEL AFONSO AGUDO NEVES
29,MARIA ANA ATAÍDE DE FIGUEIREDO CABRAL DA CAMARA,NUNO CLÁUDIO FERREIRA ROSA
30,MARIANA HENRIQUES RAPOSO MARQUES TAVARES,IRINA ADAM CRESPO QUEIRÓS
31,MARTA SOFIA SEVERO PIRES,ANDRÉ DE NORONHA BEBIANO E MOURA
32,MIGUEL DE FREITAS NUNES PEREIRA,JOEL ANDRÉ ANTUNES BERNARDO
33,MIGUEL JOSÉ DE CASTRO FAUSTINO,LUIS PEDRO AZEVEDO ALMEIDA MACHADO
34,MÓNICA HORTA DE FIGUEIREDO,ANA FILIPA GONÇALVES SIMÕES
35,NUNO CLÁUDIO FERREIRA ROSA,JOÃO MARIA ATAÍDE DE FIGUEIREDO CABRAL DA CÂMARA
36,NUNO NOGUEIRA DA SILVA,GUSTAVO LUNA BRASILEIRO
37,PEDRO MARIA ATAIDE FIGUEIREDO CABRAL DA CAMARA,MARIANA HENRIQUES RAPOSO MARQUES TAVARES
38,PEDRO MIGUEL DOS SANTOS ALBANO,NUNO CLÁUDIO FERREIRA ROSA
39,PRIAL BHARAT,VASCO MIGUEL FERNANDES ALBERTO WILTON PEREIRA
40,RICARDO MIGUEL REIS DUARTE,ANTONIO OLIVEIRA LIMA
41,RITA ISABEL LARANJEIRA COSTA RIBEIRO,MÓNICA HORTA DE FIGUEIREDO
42,RITA MARIA BRANCO DE ARAÚJO,PEDRO MARIA ATAIDE FIGUEIREDO CABRAL DA CAMARA
43,RUI MIGUEL DA FONSECA MATIAS,DIANA RIBEIRO FERREIRA
44,RUTE ALEXANDRA CASTRO LOPES,GUSTAVO LUNA BRASILEIRO
45,SAMUEL MARTINS FILIPE,ANTONIO OLIVEIRA LIMA
46,SUSANA DOS SANTOS CARAPUÇA ROSADO,ANDRÉ MIGUEL LEONG RUELA
47,TAINÁ REIS MANESCHY,ANDRÉ MIGUEL LEONG RUELA
48,TIAGO NUNES MENDES MOÇO,EMANUEL JOSÉ ALAGO RODRIGUES
49,TIAGO VASQUES ENDERENÇO,MARIANA HENRIQUES RAPOSO MARQUES TAVARES
50,TIAGO VÍTOR PINHEIRO VALENTE FARIA,AFONSO JOSÉ FERNANDES CARDOSO RODRIGUES
51,VASCO MIGUEL FERNANDES ALBERTO WILTON PEREIRA,TIAGO VASQUES ENDERENÇO

In [98]:
### IN PROGRESS ###

#Escrever numa nova worksheet do Excel
#ws_new_inc = wb.create_sheet("Incompatibilidades")

#ws_new_inc.append(list(df_pessoas.columns))
#for i in range(len(df_pessoas)):
#    ws_new_inc.append(list(df_pessoas.iloc[i,:]))

In [99]:
# Criar uma nova worksheet "Sorteio":
if 'Sorteio' in wb.sheetnames:
    wb.remove(wb['Sorteio'])

ws_new_sort = wb.create_sheet('Sorteio')
ws_new_sort.append(list(df_matches.columns))
for i in range(len(df_matches)):
    ws_new_sort.append(list(df_matches.loc[i, :]))
    

ws_new_sort.column_dimensions['A'].width = 50
ws_new_sort.column_dimensions['B'].width = 50

In [100]:
wb.save(exc_pessoas)

In [101]:
wb.close()